replicaCount: 1

image:
  repository: kenyang001/dm
  pullPolicy: Always
  tag: "milestones_131"

imagePullSecrets:
  - name: ken-docker
nameOverride: "helloworld4"
fullnameOverride: "hellworld4"
containerPort: "5000"

serviceAccount:
  create: false
  annotations: {}
  name: "ken-first-helm"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}


service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: testbyken3.dragonmetrics-static.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
