replicaCount: 1

image:
  repository: kenyang001/dm
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "milestones_131"

imagePullSecrets:
  - name: ken-docker
nameOverride: "hellworld5"
fullnameOverride: "hellworld6"
containerPort: "5000"

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podAnnotations: {}

podSecurityContext: {}


securityContext: {}


service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: testbyken3.dragonmetrics-static.com
      paths:
        - path: /
          pathType: Prefix
  tls: []


resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}
