replicaCount: 1

image:
  repository: kenyang001/dm
  pullPolicy: Always
  tag: "ops_383"

imagePullSecrets:
  - name: ken-docker
fullnameOverride: "hellworld6"  
containerPort: "5000"

serviceAccount:
  create: false
  name: "default"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: testbyken3.dragonmetrics-static.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
