apiVersion: v1
kind: Namespace
metadata:
  name: dm-api-1
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: dm-api-1
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
