replicaCount: 1

image:
  repository: dragonmetrics/dm
  pullPolicy: Always
  tag: "API.Dragonmetrics_1233"

imagePullSecrets:
  - name: dm-dockerhub-secrets
fullnameOverride: "dm-api"  
containerPort: "5000"

serviceAccount:
  create: false
  name: "default"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: testbyken2.dragonmetrics-static.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
